### ISSUE TITLE
pod-autoscaler experiment uses wrong namespace while querying deployment to recover

### ISSUE THREAD

**Issue by mikhailknyazev** [litmuschaos/litmus-go#171]
Please see chaoslib/litmus/pod-autoscaler/lib/pod-autoscaler.go:143 (for go-runner:1.8.1 )

The deployment is in AppNS while the query is for ChaosNamespace:

```
applicationClient := clients.KubeClient.AppsV1().Deployments(experimentsDetails.AppNS)
  vs
applicationClient := clients.KubeClient.AppsV1().Deployments(experimentsDetails.ChaosNamespace)
```

So when the app-under-test is in say "default" namespace, while "ChaosNamespace" is kept with the default value of "litmus":
`experimentDetails.ChaosNamespace = Getenv("CHAOS_NAMESPACE", "litmus")`
we have the following error:

`time="2020-10-12T23:07:39Z" level=error msg="Chaos injection failed due to Unable to recover the auto scaling, due to Unable to scale the, due to: Failed to get latest version of Application Deployment: deployments.apps \"nginx\" not found\n"`

**Comment by ksatchit** [comment]
Fixed by this PR: https://github.com/litmuschaos/litmus-go/pull/172
