### ISSUE TITLE
Support IAM Roles for Service Accounts for AWS related experiments

### ISSUE THREAD

**Issue by codesometech** [litmuschaos/litmus-go#244]
With IAM roles for service accounts on Amazon EKS clusters, you can associate an IAM role with a Kubernetes service account. This service account can then provide AWS permissions to the containers in any pod that uses that service account. Instead of using  AWS access key/secrets, we can use the IAM Role mapped to a service account, which is more secure way of accessing AWS services.

AWS SDK Go needs to be 1.23.13 (https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-minimum-sdk.html).

**Comment by ksatchit** [comment]
cc: @uditgaurav

**Comment by uditgaurav** [comment]
The docs for IAM Roles for Service Accounts for AWS experiment is added by: https://github.com/litmuschaos/litmus/pull/3189.
