### ISSUE TITLE
Add OnChaos mode to pod-delete experiment

### ISSUE THREAD

**Issue by gouyang** [litmuschaos/litmus-go#284]
I have a k8sprobe which mode is "OnChaos" in pod-delete experiment, it's not able to run. Seems the OnChaos mode is not ready  on pod-delete.

Ideally, the "OnChaos" mode should be enabled for all generic experiments.

**Comment by ksatchit** [comment]
cc: @ispeakc0de

**Comment by ksatchit** [comment]
OnChaos Mode is available across all generic experiments from 1.13.1.
