### ISSUE TITLE
AUT pre-check should not treat a complete-Terminated container as an error state

### ISSUE THREAD

**Issue by zergscut2017** [litmuschaos/litmus-go#287]
https://github.com/litmuschaos/litmus-go/blob/master/pkg/status/application.go
func CheckContainerStatus treat a Terminated container with reason Completed and Exit Code: 0 as error and abort the chaos experiments.
https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/:
A container in the Terminated state began execution and then either ran to completion or failed for some reason. When you use kubectl to query a Pod with a container that is Terminated, you see a reason, an exit code, and the start and finish time for that container's period of execution.
A container is in Terminated state with Reason as Completed and Exit Code: 0 is health to perform the chaos experiments on the pod. But now the code just treat them as abort.

func CheckContainerStatus(appNs, appLabel string, timeout, delay int, clients clients.ClientSets) error {

	err := retry.
		Times(uint(timeout / delay)).
		Wait(time.Duration(delay) * time.Second).
		Try(func(attempt uint) error {
			podList, err := clients.KubeClient.CoreV1().Pods(appNs).List(metav1.ListOptions{LabelSelector: appLabel})
			if err != nil || len(podList.Items) == 0 {
				return errors.Errorf("Unable to find the pods with matching labels, err: %v", err)
			}
			for _, pod := range podList.Items {
				for _, container := range pod.Status.ContainerStatuses {
					if container.State.Terminated != nil {
						return errors.Errorf("container is in terminated state")
					}
					if container.Ready != true {
						return errors.Errorf("containers are not yet in running state")
					}
					log.InfoWithValues("[Status]: The Container status are as follows", logrus.Fields{
						"container": container.Name, "Pod": pod.Name, "Readiness": container.Ready})
				}
			}
			return nil
		})
	if err != nil {
		return err
	}
	return nil
}

**Comment by ksatchit** [comment]
Are you suggesting there might be AUT instances that have completed containers - but ones that are expected - and this shouldn't hinder the success of app status check? 

It si an interesting one. @ispeakc0de @uditgaurav what are your thoughts on this

**Comment by zergscut2017** [comment]
> Are you suggesting there might be AUT instances that have completed containers - but ones that are expected - and this shouldn't hinder the success of app status check?
> 
> It si an interesting one. @ispeakc0de @uditgaurav what are your thoughts on this

Yes. It is possible that there is a pod contains several containers, and one of the container is in Terminated-Completed status. This pod should be treated as health pod and ready for chaos testing.
