### ISSUE TITLE
AUT precheck checks all the deployment with appLabel and it doesn't ignore the deployments without annotation

### ISSUE THREAD

**Issue by zergscut2017** [litmuschaos/litmus-go#288]
In 1.12.2, litmus allows the applabel applied for more than 1 deployments. Some of the deployment is added annotation that chaos=true. And annotaionCheck is true in ChaosEngine. In such scnario, the AUT precheck should only check the deployments with annotations. But the AUT precheck function checks health status for all the deployments.
pod-delete.go:
	err = status.CheckApplicationStatus(experimentsDetails.AppNS, experimentsDetails.AppLabel, experimentsDetails.Timeout, experimentsDetails.Delay, clients)
application.go:
// CheckApplicationStatus checks the status of the AUT
func CheckApplicationStatus(appNs, appLabel string, timeout, delay int, clients clients.ClientSets) error {

	switch appLabel {
	case "":
		// Checking whether applications are healthy
		log.Info("[Status]: Checking whether applications are in healthy state")
		err := CheckPodAndContainerStatusInAppNs(appNs, timeout, delay, clients)
		if err != nil {
			return err
		}
	default:
		// Checking whether application containers are in ready state
		log.Info("[Status]: Checking whether application containers are in ready state")
		err := CheckContainerStatus(appNs, appLabel, timeout, delay, clients)
		if err != nil {
			return err
		}
		// Checking whether application pods are in running state
		log.Info("[Status]: Checking whether application pods are in running state")
		err = CheckPodStatus(appNs, appLabel, timeout, delay, clients)
		if err != nil {
			return err
		}
	}
	return nil
}

**Comment by ksatchit** [comment]
Hi @zergscut2017 ! Yes this is a great point and true at this stage. A fix that ensures the app AUT health checks are restricted only to annotated workloads will be made as part of 1.13.1

**Comment by ksatchit** [comment]
This is fixed by https://github.com/litmuschaos/litmus-go/pull/293.
