### ISSUE TITLE
litmuschaos/go-runner:1.13.0 image pullback issue

### ISSUE THREAD

**Issue by rahul096d** [litmuschaos/litmus-go#316]
While running the experiments for "Pod Network Latency, Pod I/O Stress ,Pod Network Corruption and Pod Network Loss"  getting image pullback issue for '"litmuschaos/go-runner:1.13.0" image.
While running the experiment it spawns two containers.
One of the container starts with the below message : -

Events:
  Type    Reason     Age    From               Message
  ----    ------     ----   ----               -------
  Normal  Scheduled  2m17s  default-scheduler  Successfully assigned ui-consumer-service/pod-io-stress-y164fd-p5ms8 to isvchaosk8t01
  Normal  Pulled     2m16s  kubelet            Container image "litmuschaos/go-runner:1.13.0" already present on machine
  Normal  Created    2m16s  kubelet            Created container pod-io-stress-y164fd
  Normal  Started    2m16s  kubelet            Started container pod-io-stress-y164fd

The other container gives below error. When image is already present it should have pulled it like above container.
Events:

Type     Reason   Age                  From     Message
  ----     ------   ----                 ----     -------
  Normal   Pulling  76s (x4 over 2m39s)  kubelet  Pulling image "litmuschaos/go-runner:1.13.0"
  Warning  Failed   76s (x4 over 2m39s)  kubelet  Failed to pull image "litmuschaos/go-runner:1.13.0": rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.200.199:53: server misbehaving
  Warning  Failed   76s (x4 over 2m39s)  kubelet  Error: ErrImagePull
  Normal   BackOff  64s (x6 over 2m38s)  kubelet  Back-off pulling image "litmuschaos/go-runner:1.13.0"
  Warning  Failed   51s (x7 over 2m38s)  kubelet  Error: ImagePullBackOff

**Comment by ksatchit** [comment]
This reflects an issue reaching the image registry. Please retry with the right access setup & feel free to re-open this issue.
