### ISSUE TITLE
diskFill chaos test should use larger than 4K blocks writes to fill the disk

### ISSUE THREAD

**Issue by mykaul** [litmuschaos/litmus-go#334]
Filling a disk with 4K writes is somewhat slow. It should be done with 1MB or so blocks.
See https://github.com/litmuschaos/litmus-go/blob/c79b9ea0fdd2e393d95346b8017f224631bba2b9/chaoslib/litmus/disk-fill/helper/disk-fill.go#L165

**Comment by ksatchit** [comment]
Makes sense. We could make this a tunable with default set to a higher value. Thanks for the suggestion @mykaul

**Comment by uditgaurav** [comment]
closing this as the changes are added and are available in `1.13.4` onwards from - https://github.com/litmuschaos/litmus-go/pull/344
