### ISSUE TITLE
Implementation of Pod IO error chaos and improving design to increase code reuse.

### ISSUE THREAD

**Issue by arindas** [litmuschaos/litmus-go#338]
My implementation is available here: https://github.com/arindas/litmus-go/tree/master/chaoslib/litmus/pod-io-error-retval

I have created a design document based on my work up till now. It is available here: https://github.com/arindas/litmus-go/blob/master/chaoslib/litmus/pod-io-error-retval/README.md

**Comment by ispeakc0de** [comment]
Thanks, @arindas
We will definitely consider this, whenever we will add this experiment. Closing this issue for now
