### ISSUE TITLE
Support disk fill using pod exec commands

### ISSUE THREAD

**Issue by sharpyy** [litmuschaos/litmus-go#374]
##  FEATURE REQUEST

- We currently run Open Policy Agent on our K8s clusters which limit our abilities to create litmus helper pods on specific nodes. OPA has rules enabled to limit this activity. We would like to have a mode for the disk fill experiment where we would run a disk fill using the pod exec commands like it is done for pod-cpu-hog and pod-memory-hog

**Comment by neelanjan00** [comment]
Currently, we don't use exec for pod disk fill, however, you can repurpose the existing exec faults to inject disk fill using commands like `dd`. You can provide both the chaos inject and revert commands as ENVs to do it. Please refer to the fault logic and feel free to ask any doubts.
