### ISSUE TITLE
Node Restart using Redfish API

### ISSUE THREAD

**Issue by rbalagopalakrishna** [litmuschaos/litmus-go#385]
## FEATURE REQUEST

**What happened**:
Currently Litmus is using SSH based auth to execute reboot command to target nodes. for this, we are creating a keypair and adding the public key to all target nodes manually.

**What you expected to happen**:
Eliminate SSH , Use Redfish api to directly perform restart on target node using IP, UserName and Password.

EX: Reset Dell iDRAC
API request: POST request to "https://<IP>/redfish/v1/Managers/iDRAC.Embedded.1/Actions/Manager.Reset/"

**Comment by ksatchit** [comment]
@rbalagopalakrishna this is cool. Definitely somey we will explore

**Comment by gpsingh-1991** [comment]
@ksatchit I would like to work on this with @rbalagopalakrishna

**Comment by ksatchit** [comment]
Great! Thanks @gpsingh-1991 - please feel free to post your approach here!
