### ISSUE TITLE
(pod-affacted-perc): cases where pod-affacted-percentage is > 100. It was targeting same pod multiple times

### ISSUE THREAD

**Issue by ispeakc0de** [litmuschaos/litmus-go#413]
## Is this a BUG REPORT or FEATURE REQUEST?
 
 Choose one: BUG REPORT or FEATURE REQUEST

**What happened**:

- In the pod-level experiment, when pod-affected-perc is provided as > 100 then it performs the cyclic pod selections on the pod list so it selects redundant pods. target pod selection should be based on min(100,pod-affected-perc) percentage pod list

**Comment by avaakash** [comment]
@ispeakc0de we can close this issue, this PR solved this
https://github.com/litmuschaos/litmus-go/pull/429
