### ISSUE TITLE
Can use a lighter image as well (post 1.4)

### ISSUE THREAD

**Issue by ksatchit** [litmuschaos/litmus-go#5]
Can use a lighter image as well (post 1.4)

_Originally posted by @ksatchit in https://github.com/litmuschaos/litmus-go/pull/1_

**Comment by uditgaurav** [comment]
The current image used to build the Dockerfile seems to be a bit heavier than required. We can use a lightweight image like an alpine based image which could be able to build the [Dockerfile](https://github.com/litmuschaos/litmus-go/blob/master/build/litmus-go/Dockerfile).
