### ISSUE TITLE
Pod memory hog experiment fails since the stress process exited before the actual cleanup

### ISSUE THREAD

**Issue by lgelisio** [litmuschaos/litmus-go#509]
### BUG REPORT

**What happened**:
We run a Pod Memory Hog experiment with Memory Consumption tunable parameter higher than container memory limit of the target container, to provoke a container restart.
The target container restarted as expected, as soon as the memory requested by the stress-ng process exceeded the memory limit. The overall Litmus Experiment result is "**Failed**". 
As from Litmus Troubleshooting documentation this happened since the stress process inside the target container is removed before the actual cleanup. 

**What you expected to happen**:
The memory hog experiment can provoke a container restart due to OOM Killed reason. 
It should be designed in a way to give a "**Succeeded**" result in such cases, since it is an expected behaviour.

**How to reproduce it (as minimally and precisely as possible)**:
Run a Generic  Pod Memory Hog experiment with Memory Consumption tunable parameter higher than memory limit of the target container.

**Comment by neelanjan00** [comment]
We fixed it in Litmus 3.0 beta2 onwards, thanks for opening this issue!
