### ISSUE TITLE
Node Memory Hog experiment fails due to litmus helper pod eviction.

### ISSUE THREAD

**Issue by lgelisio** [litmuschaos/litmus-go#532]
BUG REPORT

**What happened**:
We run a Node Memory Hog experiment with aim to causes Memory resource exhaustion on the Kubernetes node.
Since the litmus helper pod has Best Effort QoS meanwhile the applications have Burstable QoS, as soon as the Memory pressure status is reached, the litmus helper pod is evicted and the Litmus experiment fails.

**What you expected to happen**:
As per Litmus documentation, the experiment aims to verify resiliency of applications whose replicas may be evicted due to lack of Memory resources. So the application pod has to be evicted instead of the litmus helper pod in such experiment.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy an application with Burstable or Guaranteed QoS.
Run a Generic Node Memory Hog experiment with Memory Consumption tunable parameter equal or higher than the Node available memory. The Litmus helper pod will be evicted.
![ev3](https://user-images.githubusercontent.com/104082268/174991725-58bb2603-b673-4a10-b111-fbf7b7e64197.PNG)
![ev4](https://user-images.githubusercontent.com/104082268/174991727-595fc5d5-2e44-44d0-aac3-fe7df3a49b52.PNG)

**Comment by neelanjan00** [comment]
Hi @lgelisio, thank you so much for submitting this issue!

**Comment by lorenzoelisio** [comment]
Hi @ispeakc0de, is this bug fixed in Litmus 3.0.0 beta2 version?

**Comment by neelanjan00** [comment]
This is a limitation of this fault, we may not achieve OOMKill with it, or else the helper pod will always get evicted, therefore we can only stress up to a certain threshold. If you have a better approach to handle this, feel free to re-open this issue.
