### ISSUE TITLE
bug with pod delete- pod delete is trying to delete statefulset

### ISSUE THREAD

**Issue by aabughosh** [litmuschaos/litmus-go#538]
BUG REPORT
i tried to run the pod-delete experiment  and i can see this issue
i had 2 kind of pods 1 is deployment and the other is statefulset and i want to test the delete pods test just on the deployment one but the test is failing because its checking the statefulset pods, both have same label that i need to use for the test, so im using the annotationcheck true to just run the test on the deployment
im seeing this error time=“2022-07-06T12:13:19Z” level=error msg=“Application status check failed, err: no deployment found for nginx2-0 pod”

**What happened**:
when the pod delete run it went to delete the statefulset pods, and as u can see this is the chaosengine
------------------------------------
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: engine-nginx
  namespace: default
spec:
  engineState: "active"
  annotationCheck: "true"
  chaosServiceAccount: litmus
  appinfo:
    appns: "default"
    applabel: "test=foo"
    appkind: "deployment"
  experiments:
  - name: pod-delete
------------------------------------

app kind is deployment so why it checking the statefulset?

this is the error 
error time=“2022-07-06T12:13:19Z” level=error msg=“Application status check failed, err: no deployment found for nginx2-0 pod”

**What you expected to happen**:
i expected from the test to delete just the deployment one
**How to reproduce it (as minimally and precisely as possible)**:

this is my script for repreduce 

kind create cluster
kubectl apply -f https://litmuschaos.github.io/litmus/litmus-operator-v2.9.0.yaml
kubectl apply -f "https://hub.litmuschaos.io/api/chaos/2.9.0?file=charts/generic/experiments.yaml"
apply -f https://gist.github.com/aabughosh/91ebbd1c0bda2df59603571c21d453e0#file-pod-test-yaml

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx2
  namespace: default
  labels:
    app: nginx
    test: foo
spec:
  replicas: 1
  serviceName: nginx
  selector:
    matchLabels:
      app: nginx2
  template:
    metadata:
      labels:
        app: nginx2
        test: foo
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx1
  namespace: default
  labels:
    app: nginx
    test: foo
  annotations:
    litmuschaos.io/chaos: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx1
  template:
    metadata:
      annotations:
        litmuschaos.io/chaos: "true"
      labels:
        app: nginx1
        test: foo
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

here we are creating 2 kind of nginx pods that had the same label that i used for the test but  just the deployment i put the annotationcheck

**Comment by neelanjan00** [comment]
This issue is already resolved as now we check both the labels and the parent resource of the target workload. Thanks for opening the issue.
