### ISSUE TITLE
Wrong verdict evaluation in node-restart reboot experiment

### ISSUE THREAD

**Issue by lgelisio** [litmuschaos/litmus-go#548]
**BUG REPORT**

**What happened:**
Running a **node-restart** experiment with default **REBOOT_COMMAND** value "**sudo systemctl reboot**" we observed that soon after the helper POD is deployed and the node-restart chaos has been injected successfully, the node status check is performed and the update of chaos result is done.

As you can check in the attached log, this happens after 14'' from the start of the experiment

time='2022-08-04T**08:04:53**Z' level=info msg='**Experiment Name: node-restart**'
time='2022-08-04T0**8:05:07**Z' level=info msg=**'[The End]: Updating the chaos result of node-restart experiment (EOT)**'

Since the “node-monitor-grace-period” is the time required to Kubernetes Controller Manager to marks the node as Not Ready,
when it's configured to a value higher than 14'' the node status check is performed at wrong time.

In other words Kubernetes Controller Manager has to find the node unhealthy for past “node-monitor-grace-period” **(default 40s)** before to mark it as **Not Ready**.

**What you expected to happen:**
A tunable parameter has to be used in **node-restart** experiment to define when the check of the node status has to be done according to Kubernetes Controller Manager “node-monitor-grace-period” parameter setting.

A possible solution is to reuse already existing TOTAL_CHAOS_DURATION parameter for this scope, since with current implementation it is meaningless.

**How to reproduce it (as minimally and precisely as possible):**
Check that Kubernetes Controller Manager “node-monitor-grace-period” has a 40s default value.
Run a **node-restart** experiment and watch the target node status 
( in a terminal: watch -n 1 "kubectl get node | grep <target node name>")
 
From the log experiment verify that the Litmus verdict is set before that the node status is marked as not ready

Experiment log:
[my-workflow-1664406871-3897394364.txt](https://github.com/litmuschaos/litmus-go/files/9260521/my-workflow-1664406871-3897394364.txt)
.

**Comment by ispeakc0de** [comment]
Hi @lgelisio,
You can set the RAMP_TIME ENV. Which will enable the experiment to wait for the specified ramp_time after the chaos.
I hope this will solve this issue

**Comment by ispeakc0de** [comment]
Closing this issue as this is duplicate to https://github.com/litmuschaos/litmus-go/issues/528 issue
