### ISSUE TITLE
Openshift OVN annotations propagation - container-kill experiement

### ISSUE THREAD

**Issue by ludovic-pourrat** [litmuschaos/litmus-go#551]
**What happened**:

When running the container-kill experiment in Openshit with OVN as our CNI, the helper pod is created with OVN specific annotations that are propagated from the originating Litmus POD. This result in having the helper POD not capable to reach the API server on Kubernetes.

We will be testing soon the approach to filter the OVN specific annotations. See observations below.

**What you expected to happen**:

We expected this experiment to work,

**How to reproduce it (as minimally and precisely as possible)**:

We have captured the YAML of the helper POD, and by removing the OVN specific annotations it worked.

**Anything else we need to know?**:

OVN Annotations : 

- k8s.ovn.org/pod-networks
- k8s.v1.cni.cncf.io/network-status[]

We have identified that in the pod.go the SetHelperData is propagating the annotations, see line about` chaosDetails.Annotations = pod.Annotations`

``` golang
func SetHelperData(chaosDetails *types.ChaosDetails, setHelperData string, clients clients.ClientSets) error {
	var pod *core_v1.Pod
	pod, err = clients.KubeClient.CoreV1().Pods(chaosDetails.ChaosNamespace).Get(context.Background(), chaosDetails.ChaosPodName, v1.GetOptions{})
	if err != nil {
		return err
	}

	// Get Labels
	labels := pod.ObjectMeta.Labels
	delete(labels, "controller-uid")
	delete(labels, "job-name")
	chaosDetails.Labels = labels

	switch setHelperData {
	case "false":
		return nil

	default:

		// Get Chaos Pod Annotation
		chaosDetails.Annotations = pod.Annotations
               // OVN annotations filtering should be processed here.

		// Get ImagePullSecrets
		chaosDetails.ImagePullSecrets = pod.Spec.ImagePullSecrets

		// Get Resource Requirements
		chaosDetails.Resources, err = getChaosPodResourceRequirements(chaosDetails.ChaosPodName, chaosDetails.ExperimentName, chaosDetails.ChaosNamespace, clients)
		if err != nil {
			return errors.Errorf("unable to get resource requirements, err: %v", err)
		}
		return nil
	}
}
```

**Comment by ksatchit** [comment]
@ludovic-pourrat thanks for reporting this. What is the version of OpenShift being used here? If these annotations are being propagated to helper from the experiment pod and you'd like to prevent that, you can set SET_HELPER_DATA env to false in the ChaosEngine's experiment spec (it is set to true by default). 

Ref: https://github.com/litmuschaos/litmus-go/blob/f3203a869224cb7b6020e28747c937911e2bb71a/pkg/generic/container-kill/environment/environment.go#L41

**Comment by ludovic-pourrat** [comment]
Hi,

Thanks for your answer ! We will deactivate the helper data as recommended.

I can confirm that those annotations are auto-added to the experiment POD at runtime by OVN.

Here is the version of OCP we are currently using - 4.10.16, OVN being the one attached to the release.

**Comment by ludovic-pourrat** [comment]
The experiment is reported to work when setting the `SET_HELPER_DATA` to `false`.

Thanks !
