### ISSUE TITLE
Remove Redundant Steady-State Checks in GCP VM Instance Stop experiment 

### ISSUE THREAD

**Issue by neelanjan00** [litmuschaos/litmus-go#554]
**What happened**: Redundant checks should be removed in GCP VM instance stop experiment in chaoslib

**Which file needs to be updated**: https://github.com/litmuschaos/litmus-go/blob/master/chaoslib/litmus/gcp-vm-instance-stop/lib/gcp-vm-instance-stop.go

**Comment by ashiskumarnaik** [comment]
Hi, @neelanjan00  I would like to work on this issue. Assign it to me.
