### ISSUE TITLE
Optimise Duplicate IP Check

### ISSUE THREAD

**Issue by neelanjan00** [litmuschaos/litmus-go#561]
**What happened**: 
- Duplicate IP check logic can be optimized in the network loss experiment by omitting the IP as soon as it is discovered to be duplicate.

**Where to fix this issue:** https://github.com/litmuschaos/litmus-go/blob/0bae5bec27548b6addc3ec44b72b147bb50c3997/chaoslib/litmus/network-chaos/helper/netem.go#L149

**Comment by chinmaym07** [comment]
I want to work on this .
Please assign. @neelanjan00 
I have a query like can we use a `map` to optimize the complete logic or it's just required to use a `break` .

**Comment by neelanjan00** [comment]
> I want to work on this .
> Please assign. @neelanjan00 
> I have a query like can we use a `map` to optimize the complete logic or it's just required to use a `break` .
> 

Break shall be sufficient, map is not needed.
