### ISSUE TITLE
Some questions for file experiment.go

### ISSUE THREAD

**Issue by xidian237** [litmuschaos/litmus-go#624]
## Is this a BUG REPORT or FEATURE REQUEST?
 
 Choose one: Consulting

Hello, experts,

I have some questions here, 
1. Whether the experimentname is correct, if **flag.Parse()** is not executed after line 81?
![image](https://user-images.githubusercontent.com/17851643/206989940-45f22c7d-47ad-4d0b-afc5-f7aedb3cc2ed.png)

2. There are **47** kinds of experiments in litmus from the experiment.go, does litmus support custom new types without modifying the code currently, if so, what should I do?

Regards,
Lin

**Comment by neelanjan00** [comment]
1. In the context of this use case, it is not. Until `flag.Parse` is called, the flags are not parsed into variables.
2. To create a new experiment:
    - Use the SDK to generate the artifacts that need to be edited. Instructions for this can be found [here](https://github.com/litmuschaos/litmus-go/tree/master/contribute/developer-guide).
    - Add your fault logic by modifying the generated artifacts.
    - Test your fault.

Please open another issue if you need more help!
