### ISSUE TITLE
Change the experiments "pod delete" and "pod Autoscaler" to support to Namespace dynamically

### ISSUE THREAD

**Issue by bantunes82** [litmuschaos/litmus-go#664]
FEATURE REQUEST

Hi guys, how are you ?

It will be really nice if we can assign a namespace "appns" dynamically for the experiments "pod delete" and "pod Autoscaler". 
For instance instead of defining a static value it could be a label, like we already have for the deployment using " applabel: 'app=nginx' ".

**Comment by neelanjan00** [comment]
Pod-level faults are intentionally restricted to a certain namespace to limit their blast radius. The max that you can do now is to specify a node label to target specific nodes where the target pods span across multiple nodes.

**Comment by neelanjan00** [comment]
We can discuss this more in the community Slack or a new issue, closing this issue for now. Thanks!
