### ISSUE TITLE
Log all iterations of the probe for onchaos and continuous modes configured via verbosity flag

### ISSUE THREAD

**Issue by ispeakc0de** [litmuschaos/litmus-go#678]
Log all iterations of the probe for onchaos and continuous modes configured via verbosity flag.

- The verbosity flag can be added as an optional field inside runProperties as string value, which accepts a string enum (info, debug)
- We should wait for the probe to be completed before evaluation by sending a stop request

**Comment by Nageshbansal** [comment]
Please assign this issue to me :)
